version: '3.6'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
      POSTGRES_DB: default_database
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  web:
    container_name: flask_container
    image: ubuntu:18.04
    build: .
    stdin_open: true
    tty: true

    depends_on:
      - postgres
    environment:
      env_file: .env
      VIRTUAL_HOST: auth.test.org
      # VIRTUAL_PORT: 5000
      POSTGRES_PASSWORD: 123456
      POSTGRES_PORT_5432_TCP_ADDR: postgresql
      POSTGRES_PORT_5432_TCP_PORT: 5432

    networks:
      - postgres
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app/
      - .:/usr/src/app/migrations
    env_file: .env
    links:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  web:
